# lang_data.py
languages = {
    "ar": {
        "app_title": "نظام العقارات",
        "exit": "خروج",
        "home": "الرئيسية",
        "buyer": "مشتري",
        "seller": "بائع",
        "are_you": "هل أنت مشتري أم بائع؟",
        "seller_options": "خيارات البائع",
        "new_account": "حساب جديد",
        "existing_account": "حساب قائم",
        "back": "رجوع",
        "register_new_seller": "تسجيل بائع جديد",
        "username": "اسم المستخدم",
        "password": "كلمة المرور",
        "show": "عرض",
        "hide": "إخفاء",
        "register": "تسجيل",
        "login": "تسجيل الدخول",
        "welcome": "مرحباً",
        "properties_list": "قائمة العقارات",
        "filter": "فرز",
        "most_viewed": "الأكثر مشاهدة",
        "select_images": "إضافة صور",
        "confirm_selection": "تأكيد الاختيار",
        "cancel": "إلغاء",
        "max_images": "الحد الأقصى للصور هو 6",
        "save_property": "حفظ العقار",
        "delete_account": "حذف الحساب",
        "confirm_delete": "هل أنت متأكد أنك تريد حذف الحساب؟",
        "yes": "تأكيد",
        "no": "إلغاء",
        "enter_title": "أدخل العنوان",
        "enter_price": "أدخل السعر",
        "enter_desc": "أدخل الوصف",
        "property_saved": "تم حفظ العقار بنجاح",
        "select_images_title": "اختر الصور (حتى 6)",
        "open_image": "عرض الصورة",
        "image_viewer_close": "إغلاق",
        "pay_phone_label": "ادفع إلى الرقم:",
        "payment_pending": "الرجاء دفع الرسوم على الرقم ثم أكد الدفع",
        "payment_confirmed": "تم تأكيد الدفع. تم حفظ العقار.",
    },
    "en": {
        "app_title": "Real Estate System",
        "exit": "Exit",
        "home": "Home",
        "buyer": "Buyer",
        "seller": "Seller",
        "are_you": "Are you Buyer or Seller?",
        "seller_options": "Seller Options",
        "new_account": "New Account",
        "existing_account": "Existing Account",
        "back": "Back",
        "register_new_seller": "Register New Seller",
        "username": "Username",
        "password": "Password",
        "show": "Show",
        "hide": "Hide",
        "register": "Register",
        "login": "Login",
        "welcome": "Welcome",
        "properties_list": "Properties List",
        "filter": "Filter",
        "most_viewed": "Most Viewed",
        "select_images": "Add Images",
        "confirm_selection": "Confirm Selection",
        "cancel": "Cancel",
        "max_images": "Maximum images is 6",
        "save_property": "Save Property",
        "delete_account": "Delete Account",
        "confirm_delete": "Are you sure you want to delete the account?",
        "yes": "Yes",
        "no": "No",
        "enter_title": "Enter title",
        "enter_price": "Enter price",
        "enter_desc": "Enter description",
        "property_saved": "Property saved successfully",
        "select_images_title": "Choose Images (up to 6)",
        "open_image": "Open Image",
        "image_viewer_close": "Close",
        "pay_phone_label": "Pay to number:",
        "payment_pending": "Please pay the fee to the number then confirm payment",
        "payment_confirmed": "Payment confirmed. Property saved.",
    }
}
